StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65F6B096DAE69534}" {
   Id "SSMW_RDG2_Color_Green"
   Target_en_us "RDG-2 Green"
   Target_de_de "RDG-2 Grün"
   Modified 1710667113
   Author "Interceptor"
   LastChanged "Interceptor"
  }
  CustomStringTableItem "{65F6F55055FFB0CC}" {
   Id "SSMW_RDG2_Color_Purple"
   Target_en_us "RDG-2 Purple"
   Target_de_de "RDG-2 Violett"
   Modified 1710684169
   Author "Interceptor"
   LastChanged "Interceptor"
  }
  CustomStringTableItem "{65F6B094CA61B450}" {
   Id "SSMW_RDG2_Color_Red"
   Target_en_us "RDG-2 Red"
   Target_de_de "RDG-2 Rot"
   Modified 1710666702
   Author "Interceptor"
   LastChanged "Interceptor"
  }
  CustomStringTableItem "{65F6B096C0D5B2DC}" {
   Id "SSMW_RDG2_Green_Description"
   Target_en_us "Smoke grenade (green) used by the Russian armed forces. Used for signaling, screening, and target marking."
   Target_de_de "Rauchgranate (grün) der russischen Streitkräfte. Wird zur Signalgebung, Abschirmung und Zielmarkierung verwendet."
   Modified 1710684115
   Author "Interceptor"
   LastChanged "Interceptor"
  }
  CustomStringTableItem "{65F6F5501ED1A9E8}" {
   Id "SSMW_RDG2_Purple_Description"
   Target_en_us "Smoke grenade (purple) used by the Russian armed forces. Used for signaling, screening, and target marking."
   Target_de_de "Rauchgranate (Violett) der russischen Streitkräfte. Wird zur Signalgebung, Abschirmung und Zielmarkierung verwendet."
   Modified 1710684155
   Author "Interceptor"
   LastChanged "Interceptor"
  }
  CustomStringTableItem "{65F68CF280D9939A}" {
   Id "SSMW_RDG2_Red_Description"
   Target_en_us "Smoke grenade (red) used by the Russian armed forces. Used for signaling, screening, and target marking."
   Target_de_de "Rauchgranate (rot) der russischen Streitkräfte. Wird zur Signalgebung, Abschirmung und Zielmarkierung verwendet."
   Modified 1710667355
   Author "Interceptor"
   LastChanged "Interceptor"
  }
 }
}